// server/src/services/openaiService.js
const OpenAI = require('openai');

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const generateLeaseAgreement = async (leaseTerms, propertyInfo = {}) => {
  try {
    // Check if we're in development mode or if API key is missing/invalid
    const isDevMode = process.env.NODE_ENV === 'development' || !process.env.OPENAI_API_KEY;
    const shouldUseMock = isDevMode || process.env.USE_MOCK_AI === 'true';

    if (shouldUseMock) {
      console.log('🤖 Using mock AI response for development');
      
      // Generate a realistic mock lease agreement
      const mockLease = generateMockLease(leaseTerms, propertyInfo);
      
      return {
        success: true,
        leaseDocument: mockLease,
        tokensUsed: 1500, // Mock token count
        isMockResponse: true
      };
    }

    const prompt = `
You are a legal document assistant specializing in residential lease agreements. Generate a comprehensive, professional lease agreement based on the following terms and property information.

LEASE TERMS PROVIDED:
${leaseTerms}

PROPERTY INFORMATION:
${propertyInfo.address ? `Address: ${propertyInfo.address}` : ''}
${propertyInfo.type ? `Property Type: ${propertyInfo.type}` : ''}
${propertyInfo.bedrooms ? `Bedrooms: ${propertyInfo.bedrooms}` : ''}
${propertyInfo.bathrooms ? `Bathrooms: ${propertyInfo.bathrooms}` : ''}

INSTRUCTIONS:
1. Create a complete residential lease agreement that includes all standard clauses
2. Incorporate the specific terms mentioned above
3. Use professional legal language but keep it readable
4. Include standard sections: parties, property description, term, rent, deposits, utilities, maintenance, rules, termination, etc.
5. Add placeholder fields for signatures and dates
6. Ensure compliance with general residential leasing practices
7. Format the document with clear sections and numbering

IMPORTANT: This is a template document. All parties should review with legal counsel before signing. Include this disclaimer.

Generate the complete lease agreement now:
    `;

    const response = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content: "You are a professional legal document assistant specializing in residential lease agreements. Generate comprehensive, well-structured lease agreements based on provided terms."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      max_tokens: 4000,
      temperature: 0.3, // Lower temperature for more consistent legal language
    });

    return {
      success: true,
      leaseDocument: response.choices[0].message.content,
      tokensUsed: response.usage.total_tokens,
      isMockResponse: false
    };

  } catch (error) {
    console.error('OpenAI API Error:', error);
    
    // Fallback to mock on API errors
    console.log('🤖 Falling back to mock AI response due to API error');
    const mockLease = generateMockLease(leaseTerms, propertyInfo);
    
    return {
      success: true,
      leaseDocument: mockLease,
      tokensUsed: 1500,
      isMockResponse: true,
      fallbackReason: error.message
    };
  }
};

// Mock lease generator for development/testing
const generateMockLease = (leaseTerms, propertyInfo) => {
  const currentDate = new Date().toLocaleDateString();
  const propertyAddress = propertyInfo.address || '[PROPERTY ADDRESS]';
  
  return `
RESIDENTIAL LEASE AGREEMENT
Generated by PropertyPulse AI (Development Mode)

**IMPORTANT DISCLAIMER: This is a template document generated for demonstration purposes. All parties should review with qualified legal counsel before signing. This template should not be used without proper legal review.**

═══════════════════════════════════════════

LEASE AGREEMENT

Date: ${currentDate}

This Lease Agreement ("Agreement") is entered into between:

LANDLORD: [LANDLORD NAME]
Address: [LANDLORD ADDRESS]
Phone: [LANDLORD PHONE]
Email: [LANDLORD EMAIL]

TENANT(S): [TENANT NAME(S)]
Address: [TENANT ADDRESS]
Phone: [TENANT PHONE]
Email: [TENANT EMAIL]

═══════════════════════════════════════════

1. PROPERTY DESCRIPTION

Property Address: ${propertyAddress}
${propertyInfo.type ? `Property Type: ${propertyInfo.type}` : ''}
${propertyInfo.bedrooms ? `Bedrooms: ${propertyInfo.bedrooms}` : ''}
${propertyInfo.bathrooms ? `Bathrooms: ${propertyInfo.bathrooms}` : ''}

2. LEASE TERMS (Based on your input)

${leaseTerms}

3. STANDARD LEASE PROVISIONS

3.1 USE OF PREMISES
The premises shall be used solely as a private residential dwelling.

3.2 MAINTENANCE AND REPAIRS
Tenant agrees to maintain the premises in clean and sanitary condition.

3.3 ALTERATIONS
No alterations to the premises without written consent from Landlord.

3.4 INSURANCE
Tenant is encouraged to obtain renter's insurance for personal property.

3.5 ENTRY BY LANDLORD
Landlord may enter with 24-hour notice for inspections, repairs, or showings.

3.6 TERMINATION
This lease may be terminated in accordance with local and state law.

4. SIGNATURES

Landlord: _________________________ Date: _________
Print Name: _________________________

Tenant: _________________________ Date: _________
Print Name: _________________________

Tenant: _________________________ Date: _________
Print Name: _________________________

═══════════════════════════════════════════

LEGAL DISCLAIMER: This document was generated using AI technology for demonstration purposes only. This template is not a substitute for professional legal advice. All parties should consult with qualified legal counsel familiar with local and state rental laws before executing any lease agreement. PropertyPulse and its AI service are not responsible for the legal validity or enforceability of this document.

Generated: ${currentDate}
PropertyPulse AI Lease Generator (Development Mode)
  `.trim();
};

module.exports = {
  generateLeaseAgreement
};